### ISSUE TITLE
IE/Edge/Firefox support

### ISSUE THREAD

**Issue by lrdfrd** [linuxserver/docker-emulatorjs#10]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

After weeks of not being able to get this to work, I stumbled on a blog about how there never will be support for anything other than chromium.

I have never used Chrome, now I do, only for this. 

Can someone at least put a disclamer somewhere about this, would have saved me tons of headache and time.

## Current Behavior

IE doesnt work
Edge doesnt work
firefox kindof loads but doesnt work with gamepads

Chrome works

**Comment by thelamer** [comment]
The only edge I can test is edge on Xbox and it works as it is chromium. 
I am not going to put effort into FireFox support.

**Comment by burkasaurusrex** [comment]
I haven't had any issues with Edge (chromium) on Windows

**Comment by thelamer** [comment]
1.4.3 was just released with notes about browser support.
