### ISSUE TITLE
IOS touchscreen controls.

### ISSUE THREAD

**Issue by bu2d** [linuxserver/docker-emulatorjs#13]
Unable to use touchscreen controls while on IOS.

**Comment by thelamer** [comment]
I can mash an amateur absolute positioned joystick nipple and some buttons on the page over the rendered canvas, but in general it is not how I want to solve touchscreen interface stuff. 
Really I want touch to be functional upstream in Retroarch emscripten builds so people can load in their own overlays and tweak them how they want, you also have the maintenance and support. 

The missing piece is overlay support in:
https://github.com/libretro/RetroArch/blob/master/input/drivers/rwebinput_input.c
It needs touch mapped like they do for mouse:
https://emscripten.org/docs/api_reference/html5.h.html#touch
https://github.com/libretro/RetroArch/blob/master/input/drivers/rwebinput_input.c#L261-L279
Then referenced properly in input_overlay.

It is on my radar, but I am focused now on expanding emulator compatibility and getting completely rid of emulatorjs blobs.

**Comment by thelamer** [comment]
closing ref https://github.com/linuxserver/emulatorjs/issues/22

**Comment by thelamer** [comment]
Added in 1.6.0, not perfect notably multi touch for button input is missing.
This will improve over time.
