### ISSUE TITLE
hang on load default fileset

### ISSUE THREAD

**Issue by CrazyMaker14** [linuxserver/docker-emulatorjs#17]
Hello,

after the first start try to load the default fileset. Apart from a 0 byte nds.mp4 nothing seems to happen. How can I complete the setup?

**Comment by thelamer** [comment]
The only advice I can give you is to click DL/Update again and see if it works, without the default fileset it will not function and all art assets are ingested from IPFS.

**Comment by MikeCedonis** [comment]
I went through this and had to change the folder where data is stored to /docker/emulatorjs/data/
then it all started working. It's permission related even with the correct PUID, PGID.

**Comment by thelamer** [comment]
This has got to be configuration, I cannot replicate this. If the program can write to the directory it will work.

**Comment by MikeCedonis** [comment]
Not sure what it is but I have every other docker setup the same way and can work with directories outside of the docker folder.
I'm guessing it's related to this https://github.com/linuxserver/docker-emulatorjs/issues/15

**Comment by drsassafras** [comment]
Same issue. My knowledge of such matters are not extensive, but I am also not new to this. I cant find a workaround. Not able to get past the zero bite ads.mp4, I am deploying a dockers as a part of TrueNAS Scale @truecharts

**Comment by zhcxh** [comment]
Stuck in Downloading: /data/main/videos/nds.mp4 I don't understand because of permission problems, I changed the PGID and PUID to 0, and downloaded data smoothly.

**Comment by vscrispim** [comment]
I've solved it on CasaOS by running

`sysctl -w net.ipv6.conf.all.disable_ipv6=1`

directly through emulatorjs console, because emulator were getting only ipv6 instead an ipv4 adress to download from web.
