### ISSUE TITLE
segaMS games aren't recognize by the client

### ISSUE THREAD

**Issue by dinovich** [linuxserver/docker-emulatorjs#18]
I added segaMS games, and even inside the config everything looks fine.
But when I navigate the client to the segaMS system, I get the message: "No items to load, please add some games".
I tried to add the games to config again, but it looks like it's mapped properly and still doesn't recognize any game in the client.

Any ideas?

**Comment by dinovich** [comment]
Sure thing, here it is:
https://www.textdrop.link/#/QmWFgof8CENVv62q2Trqa6nx1cNvzoLuXnciug1prVc9E5

**Comment by thelamer** [comment]
This json loads for me. 
Check your browser console make sure you don't have anything misconfigured. 
![test-min](https://user-images.githubusercontent.com/1852688/152043049-e4617b1b-53fa-46c5-a81f-473d0b8cf147.png)

**Comment by dinovich** [comment]
Figured it out, it was a caching issue. I noticed the browser pulled:
http://192.168.2.21:8196/user/config/segaMS.json
and it had empty items array in it.

Once I refreshed its cache, everything started working. I wonder if it's not a good idea to force a random query param to pull an updated JSON every time?

**Comment by thelamer** [comment]
nope, works as intended.
