### ISSUE TITLE
@eaDir on Synology NAS causes the scan to stop

### ISSUE THREAD

**Issue by dinovich** [linuxserver/docker-emulatorjs#19]
The Synology NAS sometimes creates the @eaDir folder automatically.
When trying to scan for rooms in a console's folder, if the @eaDir folder exists, I receive a message: 
"sha1sum: /data//atari2600/roms//@eaDir: Is a directory", and the scanning stops.

Only when manually deleting the folder (through SSH) I am able to scan the directory properly.

**Comment by thelamer** [comment]
Will be in the next release: 
https://github.com/linuxserver/emulatorjs/blob/master/has_files.sh#L12
