### ISSUE TITLE
Socket.io.js missing in File Management

### ISSUE THREAD

**Issue by trashken** [linuxserver/docker-emulatorjs#20]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Should take action on the file based on selection from right-click menu

## Current Behavior
Returns an error: "file /files/socket.io/socket.io.js could not be loaded" 

![2022-04-01 15_40_12-EmulatorJS Manager and 16 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/177229/161218030-f0437b5b-51a5-40ee-b598-d093d9c573c4.png)

## Steps to Reproduce
1. Load the backend (http://localhost:4000)
2. Go to File Management
3. Right-click any file (e.g. rom)
4. Select Delete

## Environment
**OS:** Unraid OS
**CPU architecture:** x86_64
**How docker service was installed:** From Community App Store

## Command used to create docker container (run/create/compose/screenshot)
![2022-04-01 15_42_07-Tower_UpdateContainer and 61 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/177229/161218275-5bf6d738-53fc-4466-8cfb-3051d31ab3db.png)

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 1000
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Initializing daemon...
go-ipfs version: 0.10.0-975d73f4e3

Repo version: 11

System version: amd64/linux

Golang version: go1.17.2

Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic
Swarm listening on /ip4/172.18.0.24/tcp/4001
Swarm listening on /ip4/172.18.0.24/udp/4001/quic
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/127.0.0.1/udp/4001/quic
Swarm announcing /ip4/172.18.0.24/tcp/4001
Swarm announcing /ip4/172.18.0.24/udp/4001/quic
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
```

**Comment by thelamer** [comment]
Yes I am aware, websockets was intentionally left out in cloudcmd middleware as it was not functional. 
The idea was that file manager was better than nothing to give the users the ability to upload stuff instead of doing everything CLI on a headless server for folder management. I built out the frontend file manager with drag and drop etc and want to port that over to server side, but simpy do not have the time for it right now.

**Comment by Emalton** [comment]
The SUBFOLDER environment variable isn't working, is this a related problem or should I create a new issue?
Attached is the JS console when changing the SUBFOLDER environment variable from `/` to `/emulatorjs/`. Help would be appreciated - thank you!!

**Comment by thelamer** [comment]
@Emalton I cannot replicate: 
`docker run --rm -it -p 3000:3000 -e SUBFOLDER='/emulatorjs/' linuxserver/emulatorjs bash`

I can hit http://localhost:3000/emulatorjs/ fine

**Comment by JohnSeabourn** [comment]
I am also having this problem where I cannot delete files via the EJS Manager.
