### ISSUE TITLE
chdman broken in latest docker build (1.7.0-ls24 x86_64)

### ISSUE THREAD

**Issue by alexdelifer** [linuxserver/docker-emulatorjs#21]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

`chdman` should be able to parse my chd files, or work at all :smile: 

## Current Behavior

$ chdman
Error relocating /usr/bin/chdman: _ZSt28__throw_bad_array_new_lengthv: symbol not found
![image](https://user-images.githubusercontent.com/1463882/161450218-72374c39-e525-4c7c-b04b-c8110f1d1dc4.png)

## Steps to Reproduce

1. `docker run -it --rm lscr.io/linuxserver/emulatorjs:1.7.0-ls24 bash`
2. `chdman`
3. Get error `Error relocating /usr/bin/chdman: _ZSt28__throw_bad_array_new_lengthv: symbol not found`
---
1. Add chd files to psx/segacd
2. Scan files in backend ui
3. Get error `Error relocating /usr/bin/chdman: _ZSt28__throw_bad_array_new_lengthv: symbol not found`

Issue is not present in `lscr.io/linuxserver/emulatorjs:1.7.0-ls23`

## Environment
**OS:**Arch Linux Current / Debian 10 Current
**CPU architecture:** x86_64
**How docker service was installed:**
Arch: `pacman -S docker`
Debian: https://docs.docker.com/engine/install/debian/

## Command used to create docker container (run/create/compose/screenshot)

`docker run -it --rm lscr.io/linuxserver/emulatorjs:1.7.0-ls24 bash`
`docker run -it --rm lscr.io/linuxserver/emulatorjs:1.7.0-ls23 bash`
`chdman`

Also occurs in my yaml, but that doesn't seem relevant...
## Docker logs

$ chdman
Error relocating /usr/bin/chdman: _ZSt28__throw_bad_array_new_lengthv: symbol not found
![image](https://user-images.githubusercontent.com/1463882/161450218-72374c39-e525-4c7c-b04b-c8110f1d1dc4.png)

Thanks for a really cool app!

**Comment by MainServerSpace** [comment]
Having the same issue and not sure what to do either.

**Comment by thelamer** [comment]
I need a bit to look into it and implement a fix, thanks for posting the working tag. Looks like they just updated the package and it is broken upstream https://pkgs.alpinelinux.org/package/edge/testing/x86_64/mame-tools
https://github.com/linuxserver/docker-emulatorjs/commit/1cb1dfe36e6940d3320a30bfae9cb1ae0d2ab3cb
I am kinda swamped right now, but might need to pin to the previous working chdman and compile it at build time.
