### ISSUE TITLE
chdman error / invalid line 1 error

### ISSUE THREAD

**Issue by FatzBomb75** [linuxserver/docker-emulatorjs#26]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Scanning folder of chd files for psx/3do/segacd/32x/ (posible saturn) would read files and add to list
oddly, pce chds add fine
Scanning as renamed iso (or other extension) pulls a hash and finishes the list. Then I manually edit the generated config, hash files and files to reflect chd once again and import each file (all are unknown this way).
The files do run succesfully in chd format.

attempting to rescan the same library (with chd extension) errors again and destroys the library

## Current Behavior
exited code chdman doesn't exist

## Steps to Reproduce

1. add chd files to psx rom directory
2. hit psx scan
3. error and scanner stops (also destroys existing list if there was one)
          Scan exited with code: 127
          /usr/local/bin/chdman: line 1: Public: command not found

## Environment
Unraid
x64
linuxserver.io CA

## Command used to create docker container (run/create/compose/screenshot)
CA install

## Docker logs
no error listed in log

**Comment by FatzBomb75** [comment]
I want to add, obviously chdman doesn't exists on the system. I tried running the script to pull the image and it fails to place it in the /usr/local/bin/ folder. Assuming permissions. I can run the command and have it download to a share folder without issue, however, emulatorjs still errors out, even if mapping the folder /usr/local/bin/ to my share.

**Comment by amazing-rando** [comment]
I'm having the exact same issue.  When I look at the chdman file that exists in the latest docker image, its clear that its just a text file containing the following line:

"Public Gateway Is Not Supported Anymore - Setup a Dedicated Gateway"

I tried moving the file over from a recent install of the Ubuntu package mame-tools, however, this did not work.

**Comment by owenb321** [comment]
I was able to work around this by opening a bash shell in the running container and running the [curl and chmod commands from the dockerfile](https://github.com/linuxserver/docker-emulatorjs/blob/b2ef3f5d329ba58be53c75b28e5d03cf05fd5455/Dockerfile#L106) that download the chdman binary.

Seems like that download step failed when the latest image was built.

**Comment by serverless83** [comment]
The Domain ipfs.infura.io isn't active anymore. Use infura-ipfs.io

**Comment by lauschin** [comment]
@serverless83 Which version fixed it for you?

**Comment by serverless83** [comment]
> @serverless83 Which version fixed it for you?

linuxserver/emulatorjs:1.7.2-ls42

**Comment by Bidonh** [comment]
> > @serverless83 Which version fixed it for you?
> 
> linuxserver/emulatorjs:1.7.2-ls42

Thanks.
I had an error with .chd files as well.
_Scan exited with code: 2
syntax error: unexpected end of file
/usr/local/bin/chdman: line 2:
unexpected EOF while looking for matching `''
/usr/local/bin/chdman: line 1:
processing game.chd_

And using that version solved that problem.
But now there's no PSX landing zone on the front end.
While nes, snes, segams, segamd, 32x have and work...

**Comment by xlorepdarkhelm** [comment]
I will also note, I had the same problem, and using the same version corrected the problem.

In the latest build, if I run chdman in the container, it is broken. But `linuxserver/emulatorjs:1.7.2-ls42` is working.

**Comment by Bidonh** [comment]
After using the PSX rom management, I noticed that when you scan for new roms, CHDMAN process **ALL the roms** not just the new ones.
Say I scanned 400 roms, later I add 100 more.
The scan will (very slowly) work on the 500 roms.

I am not sure if it is supposed to work this way but it feels wasteful to process and hash the same roms again and again.

**Comment by Hypertoken** [comment]
Not sure if my issue is exactly this as it appears this issue have been resolved with [this commit](https://github.com/linuxserver/docker-emulatorjs/commit/bfec082893bf2d08234fe0b278b72aeb8ab6356f)

When I cat chdman I get; 
```
root@8d3e8300a47b:/usr/local/bin# ls
NES20Tool  binmerge  chdman
root@8d3e8300a47b:/usr/local/bin# cat chdman
<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>openresty</center>
</body>
</html>
```
So maybe the new url is just getting slammed? 

I was able to work around the issue my manually running in my docker container;

```
curl -L "https://infura-ipfs.io/ipfs/QmUfYfuoxPgDRc9Mniv1TBXv6LXPRNArAabZo5VnzfZNtP" -o /usr/local/bin/chdman
chmod +x /urs/local/bin/chdman
```

**Comment by Bidonh** [comment]
> So maybe the new url is just getting slammed?

Maybe, the IPFS performance in bandwidth usage is terrible.

**Comment by Bidonh** [comment]
> So maybe the new url is just getting slammed?

No, I just tried the linuxserver/emulatorjs:1.7.2-ls53 container and I still got a chdman error while the linuxserver/emulatorjs:1.7.2-ls42 works great ( including with multi disks).
Except for IPFS daemon cpu+bandwidth usage...
