### ISSUE TITLE
Hide File Manager from Frontend

### ISSUE THREAD

**Issue by jeremehancock** [linuxserver/docker-emulatorjs#33]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
I would like to consider putting this behind a reverse proxy. However, I would prefer to not have the file manager exposed. Would it be possible to hide that option? I am new to emulatorjs so please forgive my ignorance if this doesn't really make sense to do so.

**Comment by thelamer** [comment]
@jeremehancock the file manager is just local browser storage specifically [browserfs](https://github.com/jvilk/BrowserFS) , it does not do anything server side unless you login with a profile, and even then it only pushes and pulls when you tell it. 
It is meant as an easy way people can upload existing sram saves from their retroarch setup or download them locally.

**Comment by jeremehancock** [comment]
@thelamer Thank you for the clarification! I really appreciate it.
