### ISSUE TITLE
Hide emulators / Show only emulators with roms

### ISSUE THREAD

**Issue by Turney1337** [linuxserver/docker-emulatorjs#4]
I was wondering if it's possible to hide specific emulator in the GUI-frontend. By default, showing all possible emulators with only having a few of them filled with ROMs, makes the GUI extremely cluttered.

Alternatively, how about showing only emulators in the frontend that have ROMs attached to it by default?

**Comment by thelamer** [comment]
Update your container and click on the DL/Update button for default in the backend.

**Comment by Turney1337** [comment]
Dang, that was quick, works like a charm - awesome, thanks a ton! =)
