### ISSUE TITLE
[FEAT] Separate Save files into Directories by System/Emulator

### ISSUE THREAD

**Issue by shanez1215** [linuxserver/docker-emulatorjs#48]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Currently, regardless of profile, all save files are dropped within the same /{profile}/saves directory. If possible, add an option to place the save files into subfolders by either emulator or system within this directory. Similar to how the roms are separated.

Current layout is
/{profile}/saves/Pokemon - Firered Version.srm
/{profile}/saves/Pokemon - Leafgreen Version.srm
/{profile}/saves/Super Mario RPG.srm

Proposed layout (at least as an option) is:
/{profile}/saves/gameboyadvance/Pokemon - Firered Version.srm
/{profile}/saves/gameboyadvance/Pokemon - Leafgreen Version.srm
/{profile}/saves/superfamicom/Super Mario RPG.srm

### Reason for change

I would like to use Syncthing to sync my emulatorjs saves with the rest of my save files. My other save files are partitioned by directories as RetroNAS, RetroArch, etc are laid out like this.

However, Syncthing cannot perform two-way syncs in any many to one configuration, as it would need to know which of the many folders to send each save file type to.

As an example, with the current layout, let's say I start a game using the rom "Pokemon - Emerald Version.gba". The save file would be dropped in the {profile}/saves directory among the other saves. Thus, there's no way for syncthing to know whether to send "Pokemon - Emerald Version.srm" to the GBA save folder or the SNES save folder (or any other one).

I've poked around the source code, but I am very new with docker/emulatorjs and cannot find where these directories are declared.

**Comment by svenEsven** [comment]
Hopefully this gets some attention, i too would love this feature
