### ISSUE TITLE
Has anyone been able to play gameboy games via safari on iOS?

### ISSUE THREAD

**Issue by FadingArabChristians** [linuxserver/docker-emulatorjs#5]
I cant seem to open any Game Boy games via Safari & Firefox on iOS. I'm using the latest build of the docker and I am running iOS 15.1

**Comment by thelamer** [comment]
Safari doesn't work, I have been loop testing fixes lately without success. Their wasm implementation in general is a pain for the emscripten devs as far as I can tell. Will update this issue when I get something working.

**Comment by thelamer** [comment]
Added safari support in 1.4.0 update your container.
