### ISSUE TITLE
[BUG] SNES emulator is choppy, constantly misses button inputs, sound is also choppy.

### ISSUE THREAD

**Issue by dnielso5** [linuxserver/docker-emulatorjs#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

SNES emulator is choppy, constantly misses button inputs, sound is also choppy.

### Expected Behavior

N64 games run fine and smooth, expected a lower end console to run better

### Steps To Reproduce

base install

### Environment

```markdown
- OS: Dietpi 8.22
- How docker service was installed: docker compose
- Hardware: RaspberryPi 4 8gig ram
```

### CPU architecture

arm64

### Docker creation

```bash
---
version: "2.1"
services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
    volumes:
      - /path/to/config:/config
      - /path/to/data:/data
    ports:
      - 3005:3000
      - 85:80
      - 4001:4001 #optional
    restart: unless-stopped
```

### Container logs

```bash
Cant find them
```

**Comment by j0nnymoe** [comment]
Does the same happen in a chromium based browser?

**Comment by dnielso5** [comment]
> Does the same happen in a chromium based browser?

Yes, but actually a different problem chrome and edge. in fact the games dont load using those two. it gets to "Loading game 100%" and then a black screen when trying SNES, N64 still works fine. Strangely my phones chrome browser works fine.

**Comment by ethanaobrien** [comment]
I believe this was fixed by this: https://github.com/libretro/RetroArch/pull/15479

I am whether or not they have updated that commit

**Comment by dnielso5** [comment]
> I believe this was fixed by this: [libretro/RetroArch#15479](https://github.com/libretro/RetroArch/pull/15479)
> 
> I am whether or not they have updated that commit

Im new to git, i dont know what that means. lol

**Comment by ethanaobrien** [comment]
>Im new to git, i dont know what that means. lol

It means this project is out of date

**Comment by dnielso5** [comment]
> > Im new to git, i dont know what that means. lol
> 
> It means this project is out of date

Thats sad, i really like this. i tried Webrcade but not what im looking for. =[

**Comment by ethanaobrien** [comment]
Keep this open. This is important

**Comment by ethanaobrien** [comment]
Keep this open. This is important

**Comment by thelamer** [comment]
I'll try to cut new cores when I get time based on the current fixes in libretro cores, am swamped though and unfortunately outside of emergency maintenance this project has taken a sideline.

**Comment by thelamer** [comment]
I took a stab at building new cores at head and unfortunately noticed some audio issues in Chromium and Safari. I hope to get some feedback here https://github.com/EmulatorJS/EmulatorJS/issues/739 but in general I can't pack these new cores if they only fix Firefox, need more time to determine what is going on.

**Comment by thelamer** [comment]
I have updated the cores I could get building today for the project: 

81_libretro
fceumm_libretro
gambatte_libretro
gearboy_libretro
genesis_plus_gx_libretro
gw_libretro
handy_libretro
mame2003_plus_libretro
mednafen_ngp_libretro
mednafen_vb_libretro
mednafen_wswan_libretro
o2em_libretro
prboom_libretro
prosystem_libretro
snes9x_libretro
stella2014_libretro
vba_next_libretro
vecx_libretro
virtualjaguar_libretro

I still cannot get picodrive working it just black screens so still no 32x but all the ones that were incompatible with the latest retroarch are still held back. 

Back to the original issue though snes audio will be perfect now.
