### ISSUE TITLE
[FEAT] Fullscreen toggle

### ISSUE THREAD

**Issue by q20** [linuxserver/docker-emulatorjs#54]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like to be able to enter fullscreen via a button in the browser.

### Reason for change

I cannot find a way to enter fullscreen.

**Comment by j0nnymoe** [comment]
Press the browser's full screen button (F11 I believe).

**Comment by q20** [comment]
> Press the browser's full screen button (F11 I believe).

I have just noticed the fullscreen overlay:

<img width="386" alt="image" src="https://github.com/linuxserver/docker-emulatorjs/assets/17024596/c86ead49-3cfe-4d74-955f-28af01405678">

Very subtle.   😉

**Comment by zyssai** [comment]
Hi, I have this overlay before going to fullscreen mode, but once I quit fullscreen with F11, overlay isn't here anymore, and F11 key doesn't work.

Is this a normal behavior?
