### ISSUE TITLE
Impossible to Download the "the default fileset"

### ISSUE THREAD

**Issue by GauthierCrp** [linuxserver/docker-emulatorjs#60]
Hello EveryOne,

I tried to install EmulatorJS on Docker. I can reach the config panel but when I click on "Download the defaut fileset to begin" the download stay stuck at the first file, and nothing more.

![image](https://github.com/linuxserver/emulatorjs/assets/30144651/ae5585cc-d933-483a-95e7-55011069b91c)

The data and config repertories are located in /home/Docker/emulatorJS/data or config. Like for other container that are working.
The container seems to have in internet access without any issue.

Any idea ? 

Many Thanks in advance.
Best Regards,
Gauthier

**Comment by thelamer** [comment]
Linking https://github.com/linuxserver/docker-emulatorjs/issues/52 as possible cause

**Comment by thelamer** [comment]
Can anyone in this thread test this: 

exec in the container and modify the config to support ipv6? 

```
docker exec -it emulatorjs bash
sed -i 's#"/ip4/127.0.0.1/tcp/5001"#["/ip4/127.0.0.1/tcp/5001","/ip6/::1/tcp/5001"]#g' /data/.ipfs/config
```

Then restart? This fixed  it for other people here: 
https://github.com/linuxserver/docker-emulatorjs/issues/52#issuecomment-1873891655

**Comment by homerr** [comment]
Please re-open if issue is not resolved

**Comment by adamcbrewer** [comment]
> ```
> docker exec -it emulatorjs bash
> sed -i 's#"/ip4/127.0.0.1/tcp/5001"#["/ip4/127.0.0.1/tcp/5001","/ip6/::1/tcp/5001"]#g' /data/.ipfs/config
> ```

This fixed the issue for me
