### ISSUE TITLE
Add URL parameter before #game

### ISSUE THREAD

**Issue by dosboxonline** [linuxserver/docker-emulatorjs#64]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add URL parameter to separate game headers and navigation menu headers. Example - https://192.168.1.1/?play=online#game

### Reason for change

"Cross-Origin-Embedder-Policy: require-corp" and "Cross-Origin-Opener-Policy: same-origin" headers only game start.

### Proposed code change

I try this in index.js file - window.location.href = '?play=online' + '#game'; but it loses data to launch the game. Can you tell me what needs to be changed in the Index.js file? Thanks.

**Comment by thelamer** [comment]
This would break entering the game in fullscreen mode which is one of my main use cases. I am still trying to figure out a non obtrusive way to keep the whole thing full screen when navigating to submenus as  Istill want to provide the user with permalinks that can be used for specific submenus and games. 

What occurs in the frontend is the scripts to launch the game are injected into the page: 

https://github.com/linuxserver/emulatorjs/blob/master/frontend/js/index.js#L142
https://github.com/linuxserver/emulatorjs/blob/master/frontend/js/index.js#L206-L208

But what you are looking for is the location change here I believe? 
https://github.com/linuxserver/emulatorjs/blob/master/frontend/js/index.js#L136

**Comment by dosboxonline** [comment]
Sorry for the off-topic post. I just took the opportunity to share. I remember someone asking about the missing logos and videos. On this sites - https://gamesdb.launchbox-app.com/#s , https://db.hfsplay.fr/games/ and this https://emumovies.com/  Logos and video snaps that the EmulatorJs download + for all other existing games.
