### ISSUE TITLE
Scan exited with code: 2  printf: usage: printf [-v var] format [arguments]  :344 +0x2b00  /NES20Tool/NES20Tool.go  )  (  main.main  ]:  running  [  1  goroutine  Unable to find NES magic.  panic:

### ISSUE THREAD

**Issue by mastan30** [linuxserver/docker-emulatorjs#8]
While scanning NES games seeing these issues, When I go into rom management and delete the last file and scan again it starts from starting and I have more than 10k files which makes it impossible to stop every 50 or 100 files and start from starting again.

**Comment by thelamer** [comment]
wtf how do you have 10k NES roms?
Given this is the second issue I will need to implement a fallback to just shasum what is there even if no header is present.

**Comment by thelamer** [comment]
Also I want to note currently there is art for like 800 titles, no duplicate logic, and nothing to filter. You will need to scroll through thousands of text lines to get to a single game. You might want to consider trimming that collection down to a US set or similar.

**Comment by mastan30** [comment]
Sure @thelamer  thanks for the suggestion, can you remove the header check for nes, so any file with .nes gets added. Also not sure why we need to scan the files , isn't there a way the emulator js pick them when the roms are added in roms folder.

**Comment by thelamer** [comment]
I have set NES roms to fallback to a shasum if it does not have a proper header.

**Comment by mastan30** [comment]
Thanks a lot @thelamer , for all the explanation for other issue and fixing this one. I just need to download latest version of docker image and It should work with new changes right?

**Comment by mastan30** [comment]
It works, thank you so much for the quick fix.
