### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by XRayBarnabey** [linuxserver/docker-emulatorjs#9]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

I'm happy that you improved metadata searcher, like on gba i had 10% and now like 90%
But still almost nothing in nds and psx :/

I'm wondering if you can add the option to import png/jpeg files in videos folder to allow us to add our own custom template as image ? <3

Thanks for the great work !!
bye

**Comment by aptalca** [comment]
Here's some info on creating and uploading assets: https://github.com/linuxserver/emulatorjs#for-asset-creators

**Comment by thelamer** [comment]
I have basically taken my personal art sets I have downloaded over time and linked them all up. If you take the time to add more art please communicate that in any way here. 
When you manually identify roms there will be data in `/data/metadata` folder you can post to pastebin or elsewhere. If you have logos/videos/backgrounds you want to submit they don't need to be in the form of code, could be as simple as a ftp or folder somewhere I can access with the data about which Sha or parent to link it to.
Just need help in general, I know the clear logos and vids are out there, just grueling work to link it all up. I have the technical know how to get this stuff pinned in IPFS and do linking, just need people to take the time to sort through and match stuff up.
